package dispatch

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
)

// EchoRuntime is a test runtime that returns a canned patch envelope.
// It requires no external API keys and is used for local Phase 1 vertical slices.
type EchoRuntime struct{}

func NewEchoRuntime() *EchoRuntime {
	return &EchoRuntime{}
}

func (r *EchoRuntime) StartSession(ctx context.Context, cfg SessionConfig) (SessionHandle, error) {
	handle := &echoHandle{
		config: cfg,
		events: make(chan RuntimeEvent, 8),
		done:   make(chan struct{}),
	}
	go handle.run(ctx)
	return handle, nil
}

type echoHandle struct {
	config SessionConfig
	events chan RuntimeEvent
	done   chan struct{}
}

func (h *echoHandle) run(ctx context.Context) {
	defer close(h.done)
	defer close(h.events)

	h.events <- RuntimeEvent{
		Type:    "stream",
		Payload: fmt.Sprintf("EchoRuntime: received request for model %s", h.config.ModelID),
	}

	h.events <- RuntimeEvent{
		Type:    "stream",
		Payload: fmt.Sprintf("System prompt length: %d chars", len(h.config.SystemPrompt)),
	}

	if h.config.UserPrompt != "" {
		h.events <- RuntimeEvent{
			Type:    "stream",
			Payload: fmt.Sprintf("User prompt length: %d chars", len(h.config.UserPrompt)),
		}
	}

	// Simulate MCP tool calls for each configured endpoint.
	for name, url := range h.config.MCPEndpoints {
		h.events <- RuntimeEvent{
			Type:    "mcp_call",
			Payload: fmt.Sprintf("Calling MCP %s at %s", name, url),
		}
		// In a real runtime this would be an actual HTTP request.
		h.events <- RuntimeEvent{
			Type:    "mcp_result",
			Payload: fmt.Sprintf("MCP %s responded with mock data", name),
		}
	}

	patchBytes, err := json.Marshal(map[string]any{
		"protocolVersion": 1,
		"patchId":         echoPatchID(h.config.SessionID),
		"sessionId":       h.config.SessionID,
		"summary":         "Echo runtime generated patch",
		"rationale":       "This is a mock patch from the EchoRuntime for local testing.",
		"files": []map[string]string{
			{
				"path":       "example.test.ts",
				"action":     "create",
				"newContent": "// Mock test generated by EchoRuntime\nconsole.log('test passed');\n",
			},
		},
	})
	if err != nil {
		h.events <- RuntimeEvent{
			Type:    "error",
			Payload: fmt.Sprintf("encode patch envelope: %v", err),
		}
		return
	}

	h.events <- RuntimeEvent{
		Type:    "patch",
		Payload: string(patchBytes),
	}

	h.events <- RuntimeEvent{
		Type:    "done",
		Payload: "echo session complete",
	}
}

func (h *echoHandle) Wait() error {
	<-h.done
	return nil
}

func (h *echoHandle) Events() <-chan RuntimeEvent {
	return h.events
}

func (h *echoHandle) Stop() error {
	return nil
}

func echoPatchID(sessionID string) string {
	if sessionID == "" {
		return "echo_patch_unscoped"
	}
	replacer := strings.NewReplacer("/", "_", "\\", "_", " ", "_", ":", "_")
	return "echo_patch_" + replacer.Replace(sessionID)
}
